version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: free_fiesta_ollama
    entrypoint: ["/bin/sh", "/app/startup/ollama-init.sh"]
    volumes:
      - ./startup:/app/startup
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

  worker:
    container_name: free_fiesta_worker
    build: ./worker
    shm_size: '1gb'
    ports:
      - "9000:9000"
      - "8001:8001"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama
    command: >
      uvicorn worker:app --host 0.0.0.0 --port 9000 --timeout-keep-alive 0

  api:
    container_name: free_fiesta_api
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - worker
    command: >
      uvicorn app:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 0

  ui:
    container_name: free_fiesta_ui
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api

  prometheus:
    image: prom/prometheus:latest
    container_name: free_fiesta_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - worker

  grafana:
    image: grafana/grafana-oss:latest
    container_name: free_fiesta_grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      
volumes:
  ollama_data:
  grafana_data: {}
